### ISSUE TITLE
What language does it support?

### ISSUE THREAD

**Issue by Carreau** [nteract/nteract.github.io#11]
That's one of the main thing I think when I get to the website. 

Of course **I** know what it does, but I really think that dropping icons of a few languages that works well  would be good. 

The gif that kind-of show what the desktop app look like is nice, but I think a **real** gif of the APP (even in the lower subsections) would be a huge plus for people to realize what it is.

**Comment by rgbkrk** [comment]
👍 to a GIF of the app and some icons from a few languages

**Comment by Carreau** [comment]
> to a GIF of the app and some icons from a few languages

Or a real cell instance backed by a (fake) kernel wit (fake) typing, until user actually click on it and modify :-P

**Comment by rgbkrk** [comment]
Well, we can make a real cell backed by a kernel from tmpnb/kernel gateway with little issue as well. :wink:

**Comment by captainsafia** [comment]
> Well, we can make a real cell backed by a kernel from tmpnb/kernel gateway with little issue as well. 😉

I actually like this idea. Not sure how big a project it would be but having a try me CodeCell at the bottom that allows you to connect to 3 different language kernels. Kill two birds with one stone and keep the UI clean.

**Comment by kelleyblackmore** [comment]
Closing issues. We now work from https://github.com/nteract/nteract.io
