### ISSUE TITLE
Edit content to show the languages that are supported

### ISSUE THREAD

**Issue by captainsafia** [nteract/nteract.github.io#15]
The copy in the first paragraph should be updated to display the list of kernels that we support.

Also, not to self that I really want to create a curated and more well-managed list of kernels that are available for use but make it a more finely curated list than the other ones that exist.

**Comment by rgbkrk** [comment]
We could provide a curated JSON file from the kernels listed at https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages, then render based on that.

**Comment by kelleyblackmore** [comment]
Closing issues. We now work from https://github.com/nteract/nteract.io
