### ISSUE TITLE
Content animates on twice

### ISSUE THREAD

**Issue by lgeiger** [nteract/nteract.github.io#21]
Happens on chrome, firefox and safari:
![nteractio](https://cloud.githubusercontent.com/assets/13285808/18420603/b01b0e9a-7876-11e6-8eb2-38f99ecf974c.gif)

**Comment by captainsafia** [comment]
@aulneau — Any idea why this might be happening?

**Comment by aulneau** [comment]
@captainsafia + @lgeiger, I see. I'll check it out and fix soon.

T
