### ISSUE TITLE
Level up the content on the home page

### ISSUE THREAD

**Issue by willingc** [nteract/nteract.github.io#28]
I would like us to group review the content on the home page.

I'll run the content section by section through a professional grammar/style checker that I have. Goals for the text:
- concise
- inspiring
- clear with a minimum of jargon
- user focused and user empowering

Let's start with these 3 text sections:
- [ ] Interactivity Where You Need It Most
- [ ] Composability for All
- [x] Open to All

Here's the first one for comment.

**Open to All**

nteract is entirely open-source and licensed under the BSD 3-Clause License. We value our users. We want you to be wildly successful, creative, and productive when using nteract. As an open project, we welcome your ideas. Please share them with us, browse our contributor documentation, and open doors to future possibilities.

**Comment by kelleyblackmore** [comment]
Closing issues. We now work from https://github.com/nteract/nteract.io
