### ISSUE TITLE
Improve download button

### ISSUE THREAD

**Issue by lgeiger** [nteract/nteract.github.io#35]
A OS sensitive download button which provides a direct download link would be really cool.

Examples:
https://atom.io/
http://electron.atom.io/#get-started
https://github.com/electron/electron.atom.io

**Comment by rgbkrk** [comment]
We control the server so we could have it direct straight to the release for that platform -- https://github.com/nteract/nteract.io

**Comment by rgbkrk** [comment]
Right now the server only proxies https://nteract.github.io, it could have a releases or downloads endpoint that does the proper handling of a redirect.

**Comment by kelleyblackmore** [comment]
Closing issues. We now work from https://github.com/nteract/nteract.io
