### ISSUE TITLE
Wrong user website. 

### ISSUE THREAD

**Issue by Carreau** [nteract/nteract.github.io#41]
For users who have they website on github it redirect to `nteract.github.io/<username>.github.io` that's because the `href` is missing the protocol so behave as a relative link.

**Comment by rgbkrk** [comment]
Where does this occur? I'm not understanding. 😕

**Comment by rgbkrk** [comment]
Separately, the site is now on https://github.com/nteract/nteract.io instead (React instead of Jekyll)

**Comment by Carreau** [comment]
/about page : ![screen shot 2017-04-28 at 14 26 30](https://cloud.githubusercontent.com/assets/335567/25547903/a6166cf8-2c1e-11e7-8cab-04c994fdd81b.png)

**Comment by Carreau** [comment]
> Separately, the site is now on https://github.com/nteract/nteract.io instead (React instead of Jekyll)

Ah, yes sorry.

**Comment by rgbkrk** [comment]
Alright, I've updated the source data and am pushing a new version of the site now. Thanks for reporting!

**Comment by rgbkrk** [comment]
It's live! I did some munging of the data from `nteract-members` to hot fix your address for now.
