### ISSUE TITLE
Kernel page suggestion

### ISSUE THREAD

**Issue by Carreau** [nteract/nteract.github.io#42]
Make all the kernels on the same page and have  buttons/fields allow to "filter" or "get into detail". 

There is (for now) only 3 kernels showing one at a time seem weird when 3 would fit on a page. 
I also go the first impression "Oh they only have python instructions for now" before seeing the buttons. 

I'm going to guess that users recognize they language logo much faster than a button with their language name on it.

**Comment by rgbkrk** [comment]
Just a note - that's now at https://github.com/nteract/nteract.io/tree/master/pages/kernels

**Comment by kelleyblackmore** [comment]
Closing issues. We now work from https://github.com/nteract/nteract.io
