### ISSUE TITLE
Download buttons should emphasize that it is alpha software

### ISSUE THREAD

**Issue by captainsafia** [nteract/nteract.github.io#6]
The download buttons should say "Download Alpha for X" so people know the software is in alpha phase.

**Comment by Carreau** [comment]
This does not seem to be fixed either for me, but I see that the commit is not in the deployed branch either. 

Did you closed on purpose ? Or was it autoclosed by github ?

I thought GitHub would autoclose only when things would be merged in master ?

**Comment by rgbkrk** [comment]
That looks like an autoclose from the commit. This was deployed earlier today, so it's certainly closed now. Thanks all!
